### ISSUE TITLE
Great instructions, a few minor points (install karma-cli and import fakeAsync)

### ISSUE THREAD

**Issue by brianwoelfel** [raphael-volt/ng2-testable-lib#10]
I had trouble getting everything to work at first, and wanted to share some notes in case anyone else is going to run this.

1.  Before I can run "karma init", I had to install karma-cli.  
     npm install -g karma-cli

2.  In order to get sample.spec.ts to compile without errors for fakeAsync and tick, I had to add this to the top:
import { fakeAsync, tick } from '@angular/core/testing';

3.  The original code generated from yo has sample.component.spec.ts, which purposely has a failed test in it.  I didn't realize this existed, and when I ran "npm test" I was really confused why the test count was bigger and where the failure was coming from.  Everything made sense once I remembered this old test was there.

Otherwise everything worked great, thanks for putting this together.

- Brian

**Comment by raphael-volt** [comment]
Fixed using the new approach that use angular5  test environment.
