### ISSUE TITLE
Compiling but not running tests

### ISSUE THREAD

**Issue by sgentile** [raphael-volt/ng2-testable-lib#11]
When I run npm test I get the following:

07 09 2017 11:26:34.463:INFO [compiler.karma-typescript]: Compiling project using Typescript 2.3.0
07 09 2017 11:26:37.634:INFO [compiler.karma-typescript]: Compiled 79 files in 3144 ms.

But it's not running any of my spec.ts files ?

**Comment by btgoodwin** [comment]
I have the same problem.

**Comment by raphael-volt** [comment]
Hi, I have completely changed my approach to generate libraries due to angular5 library package format compatibility.

Hope it helps.
