### ISSUE TITLE
Add  more frameworks to do testing

### ISSUE THREAD

**Issue by tonivj5** [raphael-volt/ng2-testable-lib#4]
Thanks for your great setup! It's fantastic 👍 

I think would be awesome to have various frameworks to do testing and to can choose one

For example, tutorials for: jest, mocha/chai, AVA

**Comment by raphael-volt** [comment]
Thanks for your interest.

I have never used testing frameworks other than jasmine.

So if If you are motivated to do it, pull requests are welcome!

**Comment by raphael-volt** [comment]
Won't fix.
