### ISSUE TITLE
Fails to load templateUrl or styleUrl of component

### ISSUE THREAD

**Issue by lohiaad** [raphael-volt/ng2-testable-lib#8]
Hi,

Its work with component having inline template and style but fails with external template and styles.

Error: This test module uses the component DashboardComponent which is using a "templateUrl" or "styleUrls", but they were never compiled. Please call "TestBed.compileComponents" before your test.

##sample code
```

import { ComponentFixture, TestBed, async } from '@angular/core/testing';
import { By } from '@angular/platform-browser';
import { DebugElement } from '@angular/core';
import { DashboardComponent } from './dashboard.component';

describe('DashboardComponent', () => {

  let comp: DashboardComponent;
  let fixture: ComponentFixture<DashboardComponent>;
  let de: DebugElement;
  let el: HTMLElement;

  beforeEach(async(() => {

    TestBed.configureTestingModule({
      declarations: [DashboardComponent]
    }).compileComponents();

  }));

  beforeEach(() => {

    fixture = TestBed.createComponent(DashboardComponent);

    comp = fixture.componentInstance; // BannerComponent test instance

    fixture.detectChanges()
   
  });

  it('Should be true', () => {
    expect(comp).toBeTruthy();
  });
});
```

thanks

**Comment by leopic** [comment]
I'm running into the same issue, any ideas here @raphael-volt ?

**Comment by higorn** [comment]
Same to me.

**Comment by IckleChris** [comment]
Same issue here.

I have (from the root)

- src
    - components
        - my-component
            - my-component.component.ts
            - my-component.component.spec.ts
            - my-component.component.html

When `karma-typescript-angular2-transform` rewrites the template path, it changes it to `/base/src/components/my-component/my-component.component.html` which then leads to the error `Failed to load src/components/my-component/my-component.component.html`

**Comment by raphael-volt** [comment]
Hi,

Sorry, I currently have no time for this project. 

I invite you to use the [Nrwl Extensions for Angular](https://nrwl.io/nx) for testing, and the [ng-packagr](https://github.com/dherges/ng-packagr) to compile your libraries.

And thanks for your interest.

**Comment by dgroh** [comment]
@raphael-volt  could you please write this in the README, that this package is discontinued?

**Comment by cbalit** [comment]
I fix the issue by adding the following line in the files section of the karma config file
`'src/**/*.html'`

**Comment by leopic** [comment]
Thank you @cbalit, that didn't quite work for me as it was loading HTML files from the inner node_modules directory, so I restricted to our own components' directory and that did the trick, yay!

**Comment by raphael-volt** [comment]
Take a look of the new approach, that will fix the karma loader problems.
